version: "3.8"
services:
  frigate-telegram-ws:
    build:
      context: https://github.com/TandyTuscon/frigate-telegram-ws.git
      dockerfile: Dockerfile
    container_name: frigate-telegram-ws
    restart: always
    volumes:
      - /home/max/frigate-telegram-ws/config:/root/config
